def signals():

    gender_age = ["a baby boy","a baby girl","a girl", "a boy", "a woman", "a man", "an elderly man", "an elderly woman"]
    # CONTEXT
    """
    locContext: Location or Scene contexts are extracted from "The Urban Setting Thesaurus: A Writer's Guide to City Spaces[Puglisi et al.]
    and "The Rural Setting Thesaurus: A Writer's Guide to Personal and Natural Places[Puglisi et al.]"
    """
    locContext = [
    'alley', 'bank', 'big city street', 'board room', 'car accident', 'car wash',
              'cheap motel', 'community center', 'condemned apartment building', 'construction site',
              'courtroom', 'elevator', 'emergency room', 'empty lot', 'factory', 'fire station', 'fitness center'
              , 'funeral home', 'gas station', 'hair salon', 'homeless shelter', 'hospital room', 'hotel room'
              , 'juvenile detention center', 'laundromat', 'library', 'mechanics shop', 'military base'
              , 'morgue', 'newsroom', 'nursing home', 'office cubicle', 'park', 'parking garage', 'parking lot'
              , 'penthouse suite', 'police station', 'prison cell', 'psychiatric ward', 'public restroom'
              , 'refugee camp', 'run-down apartment', 'sewers', 'small town street', 'spa', 'tattoo parlor',
              'therapist office', 'underpass', 'vet clinic', 'waiting room',
              'bakery', 'bar', 'casual dining restaurant', 'coffeehouse', 'deli', 'diner', 'fast food restaurant',
              'ice cream parlor', 'pub',
              'antiques shop', 'bazaar', 'bookstore', 'convenience store', 'flower shop', 'grocery store',
              'hardware store', 'jewelry store', 'liquor store', 'pawn shop', 'pet store', 'psychics shop',
              'shopping mall', 'thrift store', 'used car dealership',
              'amusement park', 'art gallery', 'art studio', 'ballroom', 'black-tie event', 'bowling alley',
              'carnival funhouse', 'casino', 'circus', 'golf course', 'green room', 'indoor shooting range',
              'movie theater', 'museum', 'nightclub', 'outdoor pool', 'outdoor skating rink',
              'parade', 'performing arts theater', 'pool hall', 'race track (horses)', 'rec center',
              'recording studio', 'rock concert', 'skate park', 'ski resort', 'sporting event stands',
              'vegas stage show', 'water park', 'zoo',
              'airplane', 'airport', 'ambulance', 'city bus', 'cruise ship', 'fishing boat', 'limousine',
              'marina', 'military helicopter', 'old pick-up truck', 'police car', 'submarine', 'subway train',
              'subway tunnel', 'tank', 'taxi', 'train station', 'truck stop', 'yacht',
              'attic', 'backyard', 'basement', 'bathroom', 'birthday party', 'block party', 'bomb shelter',
              'chicken coop', 'childs bedroom', 'flower garden', 'garage', 'greenhouse', 'group foster home',
              'halloween party', 'house fire', 'house party', 'kitchen', 'living room', 'man cave', 'mansion',
              'motor home', 'nursery', 'outhouse', 'patio deck', 'root cellar', 'secret passageway',
              'teenager bedroom', 'toolshed', 'trailer park', 'tree house', 'unerground storm shelter',
              'vegetable patch', 'wake', 'wine cellar', 'workshop',
              'boarding school', 'custodial supply room', 'dorm room', 'elementary school classroom',
              'gymnasium', 'high school cafeteria', 'high school hallway', 'locker room', 'playground',
              'preschool', 'principal office', 'prom', 'school bus', 'science lab', 'teacher lounge',
              'university lecture hall', 'university quad',
              'abandoned mine', 'ancient ruins', 'archery range', 'barn', 'beach party', 'campsite',
              'church', 'country road', 'county fair', 'farmer market', 'graveyard', 'hunting cabin',
              'landfill', 'lighthouse', 'mausoleum', 'orchard', 'pasture', 'quarry', 'ranch', 'rodeo',
              'salvage yard', 'slaughterhouse', 'summer camp', 'taxidermist', 'wedding reception', 'winery',
              'arctic tundra', 'badlands', 'beach', 'canyon', 'cave', 'creek', 'desert', 'forest',
              'grotto', 'hiking trail', 'hot springs', 'lake', 'marsh', 'meadow', 'moors', 'mountains', 'ocean',
              'pond', 'rainforest', 'river', 'swamp', 'tropical island', 'waterfall'
              ]

    """
    Activities are extracted from ucf_101 [https://www.crcv.ucf.edu/data/UCF101.php],
    HMDB [https://serre-lab.clps.brown.edu/resource/hmdb-a-large-human-motion-database/] with 51 categories
    and kinetic_700 [https://github.com/cvdfoundation/kinetics-dataset?tab=readme-ov-file].
    """

    ucf_HMDB = [
"is applying eye makeup",
"is applying lipstick",
"is archery",
"is crawling",
"is balance beaming",
"is band marching",
"is baseball pitching",
"is basketball shooting",
"is basketball dunking",
"is bench pressing",
"is biking",
"is billiards shooting",
"is blow drying hair",
"is blowing candles",
"is bodyweight squatting",
"is playing bowling",
"is boxing punching bag",
"is boxing speed bag",
"is breaststroke swimming",
"is brushing teeth",
"is cleaning and jerking",
"is cliff diving",
"is cricket bowling",
"is cricket shooting",
"is cutting in the kitchen",
"is diving",
"is drumming",
"is fencing",
"is doing field hockey penalty",
"is doing floor gymnastics",
"is frisbee catching",
"is front crawling",
"is golf swinging",
"is doing a haircut",
"is hammer throwing",
"is hammering",
"is doing handstand push-ups",
"is handstand walking",
"is head massaging",
"is high jumping",
"is horse racing",
"is horse riding",
"is doing hula hoop",
"is ice dancing",
"is javelin throwing",
"is juggling balls",
"is jump roping",
"is doing jumping jacks",
"is kayaking",
"is knitting",
"is doing long jump",
"is doing lunges",
"is doing a military parade",
"is mixing batter",
"is mopping the floor",
"is doing nunchucks",
"is doing parallel bars",
"is pizza tossing",
"is playing guitar",
"is playing piano",
"is playing tabla",
"is playing violin",
"is playing cello",
"is playing daf",
"is playing dhol",
"is playing flute",
"is playing sitar",
"is doing pole vault",
"is doing pommel horse",
"is doing pull-ups",
"is punching",
"is doing push-ups",
"is rafting",
"is rock climbing",
"is rope climbing",
"is rowing",
"is doing salsa spins",
"is shaving beard",
"is doing shot put",
"is skateboarding",
"is skiing",
"is skijetting",
"is skydiving",
"is soccer juggling",
"is taking a soccer penalty",
"is doing still rings",
"is sumo wrestling",
"is surfing",
"is swinging",
"is playing table tennis",
"is doing tai chi",
"is doing a tennis swing",
"is throwing the discus",
"is trampoline jumping",
"is typing",
"is doing uneven bars",
"is volleyball spiking",
"is walking with a dog",
"is doing wall push-ups",
"is writing on a board",
"is doing Yo-Yo tricks",
"is smoking",
"is eating",
"is drinking",
"is cartwheeling",
"is clapping hands",
"is climbing",
"is climbing stairs",
"is diving",
"is falling on the floor",
"is backhanding",
"is flipping",
"is handstanding",
"is jumping",
"is pulling up",
"is pushing up",
"is running",
"is sitting down",
"is sitting up",
"is somersaulting",
"is standing up",
"is turning",
"is walking",
"is waving",
"is brushing hair",
"is catching",
"is drawing a sword",
"is dribbling",
"is golfing",
"is hitting something",
"is kicking a ball",
"is picking",
"is pouring",
"is pushing something",
"is riding a bike",
"is riding a horse",
"is shooting a ball",
"is shooting a bow",
"is shooting a gun",
"is swinging a baseball bat",
"is sword exercising",
"is throwing",
"is fencing",
"is hugging",
"is kicking someone",
# "is kissing", # have it in kinetic
"is punching",
"is shaking hands",
"is sword fighting"
    ]

    kinetic = [
'is abseiling',
'is acting in a play',
'is adjusting glasses',
'is air drumming',
'is wrestling alligators',
'is answering questions',
'is applauding',
'is applying cream',
'is conducting archaeological excavation',
'is practicing archery',
'is arguing',
'is arm wrestling',
'is arranging flowers',
'is making an arrest',
'is assembling a bicycle',
'is assembling a computer',
'is attending a conference',
'is conducting an auction',
'is waking up a baby',
'is performing a backflip',
'is baking cookies',
'is bandaging',
'is barbecuing',
'is bartending',
'is base jumping',
'is bathing a dog',
'is training with battle ropes',
'is beatboxing',
'is beekeeping',
'is feeling excited',
'is experiencing zero gravity',
'is belly dancing',
'is bench pressing',
'is bending backward',
'is bending metal',
'is biking through snow',
'is blasting sand',
'is blending fruit',
'is blow-drying hair',
'is blowing bubble gum',
'is blowing glass',
'is blowing leaves',
'is blowing nose',
'is blowing out candles',
'is bobsledding',
'is bodysurfing',
'is bookbinding',
'is bottling'
'is bouncing a ball (not juggling)',
'is bouncing on a bouncy castle',
'is bouncing on a trampoline',
'is bowling',
'is braiding hair',
'is breading or breadcrumbing',
'is breakdancing',
'is breaking boards',
'is breaking glass',
'is breathing fire',
'is brush painting',
'is brushing the floor',
'is brushing hair',
'is brushing teeth',
'is building a cabinet',
'is building with Lego',
'is building a sandcastle',
'is building a shed',
'is bulldozing',
'is bungee jumping',
'is burping',
'is busking',
'is calculating',
'is doing calligraphy',
'is canoeing or kayaking',
'is practicing capoeira',
'is capsizing',
'is stacking cards',
'is throwing cards',
'is carrying a baby',
'is carrying weight',
'is cartwheeling',
'is carving ice',
'is carving marble',
'is carving a pumpkin',
'is carving wood with a knife',
'is casting a fishing line',
'is catching fish',
'is catching or throwing a baseball',
'is catching or throwing a frisbee',
'is catching or throwing a softball',
'is celebrating',
'is changing gears in a car',
'is changing oil',
'is changing a wheel (not on a bike)',
'is chasing',
'is checking tires',
'is checking a watch',
'is cheerleading',
'is chewing gum',
'is chiseling stone'
'is chiseling wood',
'is chopping meat',
'is chopping wood',
'is clam digging',
'is clapping',
'is making clay pottery',
'is performing clean and jerk',
'is cleaning gutters',
'is cleaning a pool',
'is cleaning shoes',
'is cleaning a toilet',
'is cleaning windows',
'is climbing a rope',
'is climbing a ladder',
'is climbing a tree',
'is closing a door',
'is coloring in',
'is combing hair',
'is contact juggling',
'is contorting',
'is cooking chicken',
'is cooking an egg',
'is cooking on a campfire',
'is cooking sausages (not on a barbecue)',
'is cooking scallops',
'is cosplaying',
'is coughing',
'is counting money',
'is country line dancing',
'is cracking their back',
'is cracking their knuckles',
'is cracking their neck',
'is crawling like a baby',
'is crocheting',
'is crossing their eyes',
'is crossing a river',
'is crying',
'is dancing cumbia',
'is curling (sport)',
'is curling their eyelashes',
'is curling hair',
'is cutting an apple',
'is cutting a cake',
'is cutting nails',
'is cutting an orange',
'is cutting a pineapple',
'is cutting a watermelon',
'is dancing ballet',
'is dancing the Charleston',
'is dancing Gangnam Style',
'is dancing the Macarena',
'is deadlifting',
'is dealing cards',
'is decorating the Christmas tree',
'is doing decoupage',
'is delivering mail',
'is digging',
'is dining',
'is directing traffic',
'is playing disc golf',
'is cliff diving',
'is docking a boat',
'is playing dodgeball',
'is doing aerobics',
'is doing a jigsaw puzzle',
'is doing laundry',
'is doing nails',
'is doing sudoku',
'is drawing',
'is dribbling a basketball',
'is drinking shots',
'is driving a car',
'is driving a tractor',
'is drooling',
'is drop kicking',
'is drumming their fingers',
'is dumpster diving',
'is dunking a basketball',
'is dyeing eyebrows',
'is dyeing hair',
'is eating a burger',
'is eating cake',
'is eating carrots',
'is eating chips',
'is eating doughnuts',
'is eating a hotdog',
'is eating ice cream',
'is eating nachos',
'is eating spaghetti',
'is eating watermelon',
'is hunting eggs',
'is embroidering',
'is entering a church',
'is exercising their arms',
'is exercising with an exercise ball'
'is extinguishing a fire',
'is faceplanting',
'is falling off a bike',
'is falling off a chair',
'is feeding birds',
'is feeding fish',
'is feeding goats',
'is fencing (sport)',
'is fidgeting',
'is filling a cake',
'is filling eyebrows',
'is finger snapping',
'is fixing a bicycle',
'is fixing hair',
'is flint knapping',
'is flipping a bottle',
'is flipping a pancake',
'is fly tying',
'is flying a kite',
'is folding clothes',
'is folding napkins',
'is folding paper',
'is doing front raises',
'is frying vegetables',
'is gargling',
'is geocaching',
'is getting a haircut',
'is getting a piercing',
'is getting a tattoo',
'is giving or receiving an award',
'is gold panning',
'is golf chipping',
'is golf driving',
'is golf putting',
'is gospel singing in church',
'is grinding meat',
'is grooming a cat',
'is grooming a dog',
'is grooming a horse',
'is doing gymnastics tumbling',
'is doing a hammer throw',
'is hand washing clothes',
'is doing a headstand',
'is headbanging',
'is headbutting',
'is helmet diving',
'is herding cattle',
'is high fiving',
'is doing a high jump',
'is doing a high kick',
'is doing historical reenactment',
'is hitting a baseball',
'is doing a hockey stop',
'is holding a snake',
'is home roasting coffee',
'is playing hopscotch',
'is hoverboarding',
'is huddling',
'is hugging (not a baby)',
'is hugging a baby',
'is hula hooping',
'is hurdling',
'is doing hurling (sport)',
'is ice climbing',
'is ice fishing',
'is ice skating',
'is ice swimming',
'is inflating balloons',
'is installing carpet',
'is ironing',
'is ironing hair',
'is doing a javelin throw',
'is jaywalking',
'is jetskiing',
'is jogging',
'is juggling balls',
'is juggling fire',
'is juggling a soccer ball',
'is jumping on a bicycle',
'is jumping into a pool',
'is doing jumping jacks',
'is jumping on a sofa',
'is doing jumpstyle dancing',
'is karaoke',
'is kicking a field goal',
'is kicking a soccer ball',
'is kissing',
'is kitesurfing',
'is knitting',
'is krumping',
'is land sailing',
'is laughing',
'is lawn mower racing',
'is laying bricks',
'is laying concrete',
'is laying decking',
'is laying stone',
'is laying tiles',
'is doing leatherworking',
'is letting go of a balloon',
'is licking',
'is lifting a hat',
'is lighting a candle',
'is lighting a fire',
'is listening with headphones',
'is lock picking',
'is doing a long jump',
'is longboarding',
'is looking at a phone',
'is looking in a mirror',
'is doing luge',
'is doing a lunge',
'is making a cake',
'is making a sandwich',
'is making balloon shapes',
'is making bubbles',
'is making cheese',
'is making horseshoes',
'is making jewelry',
'is making latte art',
'is making paper airplanes',
'is making pizza',
'is making slime',
'is making a snowman',
'is making sushi',
'is making tea',
'is making the bed',
'is marching',
'is doing a marriage proposal',
'is massaging the back',
'is massaging the feet',
'is massaging the legs',
'is massaging the neck',
'is massaging a person\'s head',
'is metal detecting',
'is milking a cow',
'is milking a goat',
'is mixing colors',
'is moonwalking',
'is mopping the floor',
'is mosh pit dancing',
'is motorcycling',
'is doing mountain climber exercise',
'is moving a baby',
'is moving a child',
'is moving furniture',
'is mowing the lawn',
'is mushroom foraging',
'is needle felting',
'is news anchoring',
'is opening a bottle (not wine)',
'is opening coconuts',
'is opening a door',
'is opening a present',
'is opening the refrigerator',
'is opening a wine bottle',
'is packing',
'is paragliding',
'is parasailing',
'is doing parkour',
'is passing an American football (in a game)',
'is passing an American football (not in a game)',
'is passing a soccer ball',
'is peeling apples',
'is peeling a banana',
'is peeling potatoes',
'is collecting garbage',
'is petting an animal (not a cat)',
'is petting a cat',
'is petting a horse',
'is photobombing',
'is photocopying',
'is picking apples',
'is picking blueberries',
'is having a pillow fight',
'is pinching',
'is pirouetting',
'is planing wood',
'is planting trees',
'is plastering',
'is playing the accordion',
'is playing American football',
'is playing badminton',
'is playing the bagpipes',
'is playing basketball',
'is playing the bass guitar',
'is playing beer pong',
'is playing billiards',
'is playing blackjack',
'is playing cards',
'is playing the cello',
'is playing checkers',
'is playing chess',
'is playing the clarinet',
'is playing with a controller',
'is playing cricket',
'is playing the cymbals',
'is playing darts',
'is playing the didgeridoo',
'is playing dominoes',
'is playing the drums',
'is playing field hockey',
'is playing the flute',
'is playing the gong',
'is playing the guitar',
'is playing hand clapping games',
'is playing the harmonica',
'is playing the harp',
'is playing ice hockey',
'is playing the keyboard',
'is playing kickball',
'is playing laser tag',
'is playing the lute',
'is playing mahjong',
'is playing the maracas',
'is playing marbles',
'is playing monopoly',
'is playing netball',
'is playing the nose flute',
'is playing the oboe',
'is playing the ocarina',
'is playing the organ',
'is playing paintball',
'is playing pan pipes',
'is playing the piano',
'is playing the piccolo',
'is playing pinball',
'is playing ping pong',
'is playing poker',
'is playing polo',
'is playing the recorder',
'is playing road hockey',
'is playing rounders',
'is playing with a Rubik\'s Cube',
'is playing the saxophone',
'is playing scrabble',
'is playing shuffleboard',
'is playing a slot machine',
'is playing squash or racquetball',
'is playing tennis',
'is playing the trombone',
'is playing the trumpet',
'is playing the ukulele',
'is playing the violin',
'is playing volleyball',
'is playing with trains',
'is playing the xylophone',
'is poaching eggs',
'is poking a belly button',
'is pole vaulting',
'is polishing furniture',
'is polishing metal',
'is popping balloons',
'is pouring beer',
'is pouring milk',
'is pouring wine',
'is preparing a salad',
'is presenting a weather forecast',
'is pretending to be a statue',
'is doing pull-ups',
'is pulling an espresso shot',
'is playing a rope pulling game',
'is pumping a fist',
'is pumping gas',
'is hitting a punching bag',
'is punching a person (boxing)',
'is doing a push-up',
'is pushing a car',
'is pushing a cart',
'is pushing a wheelbarrow',
'is pushing a wheelchair',
'is putting in contact lenses',
'is putting on eyeliner',
'is putting on foundation',
'is putting on lipstick',
'is putting on mascara',
'is putting on a sari',
'is putting on shoes',
'is putting wallpaper on a wall',
'is raising eyebrows',
'is reading a book',
'is reading a newspaper',
'is recording music',
'is repairing a puncture',
'is riding a bike',
'is riding a camel',
'is riding an elephant',
'is riding a mechanical bull'
'is riding a mule',
'is riding or walking with a horse',
'is riding a scooter',
'is riding a snow blower',
'is riding a unicycle',
'is ripping paper',
'is roasting marshmallows',
'is roasting a pig',
'is robot dancing',
'is rock climbing',
'is playing rock-paper-scissors',
'is roller skating',
'is rolling eyes',
'is rolling pastry',
'is doing rope pushdowns',
'is running on a treadmill',
'is sailing',
'is salsa dancing',
'is saluting',
'is sanding the floor',
'is sanding wood',
'is making sausages',
'is sawing wood',
'is scrambling eggs',
'is scrapbooking',
'is scrubbing the face',
'is scuba diving',
'is seasoning food',
'is separating eggs',
'is setting the table',
'is sewing',
'is shaking hands',
'is shaking the head',
'is shaping bread dough',
'is sharpening knives',
'is sharpening a pencil',
'is shaving the head',
'is shaving legs',
'is shearing sheep',
'is shining a flashlight',
'is shining shoes',
'is doing the shoot dance',
'is shooting basketball',
'is shooting a goal (soccer)',
'is shooting off fireworks',
'is shopping',
'is doing the shot put',
'is shouting',
'is shoveling snow',
'is shredding paper',
'is shucking oysters',
'is shuffling cards',
'is shuffling feet',
'is doing a side kick',
'is sieving',
'is sign language interpreting',
'is participating in a silent disco',
'is singing',
'is sipping from a cup',
'is doing sit-ups',
'is skateboarding',
'is performing ski ballet',
'is ski jumping',
'is cross-country skiing',
'is doing mono skiing',
'is doing slalom skiing',
'is skipping rope',
'is skipping stones',
'is skydiving',
'is slacklining',
'is slapping',
'is participating in sled dog racing',
'is sleeping',
'is slicing an onion',
'is smashing',
'is smelling feet',
'is smoking',
'is smoking a hookah',
'is smoking a pipe',
'is doing snatch weightlifting',
'is sneezing',
'is snorkeling',
'is snowboarding',
'is snowkiting',
'is snowmobiling',
'is somersaulting',
'is spelunking',
'is spinning plates',
'is spinning poi',
'is splashing water',
'is spray painting',
'is spraying',
'is springboard diving',
'is square dancing',
'is doing squats',
'is squeezing an orange',
'is stacking cups',
'is stacking dice',
'is standing on hands'
'is staring',
'is participating in steer roping',
'is steering a car',
'is sticking tongue out',
'is stomping grapes',
'is stretching an arm',
'is stretching a leg',
'is sucking a lolly',
'is surfing a crowd',
'is surfing water',
'is surveying',
'is sweeping the floor',
'is swimming backstroke',
'is swimming breaststroke',
'is swimming butterfly stroke',
'is swimming front crawl',
'is swimming with dolphins',
'is swimming with sharks',
'is swing dancing',
'is swinging a baseball bat',
'is swinging on something',
'is sword fighting',
'is sword swallowing',
'is tackling',
'is tagging graffiti',
'is practicing tai chi',
'is taking a photo',
'is talking on a cell phone',
'is tango dancing',
'is tap dancing',
'is tapping a guitar',
'is tapping a pen',
'is tasting beer',
'is tasting food',
'is tasting wine',
'is testifying',
'is texting',
'is threading a needle',
'is throwing an axe',
'is throwing a ball (not baseball or American football)',
'is throwing a discus',
'is throwing a knife',
'is throwing snowballs',
'is throwing a tantrum',
'is throwing a water balloon',
'is tickling',
'is tie-dying',
'is tightrope walking',
'is tiptoeing',
'is tobogganing',
'is tossing a coin',
'is tossing a salad',
'is training a dog',
'is trapezing',
'is treating wood',
'is trimming or shaving a beard',
'is trimming shrubs',
'is trimming trees',
'is performing the triple jump',
'is twiddling fingers',
'is tying a bow tie',
'is tying a knot (not on a tie)',
'is tying a necktie',
'is tying shoe laces',
'is unboxing',
'is uncorking champagne',
'is unloading a truck',
'is using a microscope',
'is using a paint roller',
'is using a power drill',
'is using a sledgehammer',
'is using a wrench',
'is using an ATM',
'is using a bagging machine',
'is using a circular saw',
'is using an inhaler',
'is using a megaphone',
'is using puppets',
'is using a remote controller (not for gaming)',
'is using a Segway',
'is vacuuming a car',
'is vacuuming the floor',
'is visiting the zoo',
'is wading through mud',
'is wading through water',
'is waiting in line',
'is waking up',
'is walking on stilts',
'is walking the dog',
'is walking through snow',
'is walking with crutches',
'is washing dishes',
'is washing feet',
'is washing hair',
'is washing hands',
'is watching TV',
'is water skiing',
'is water sliding',
'is watering plants',
'is waving hand',
'is waxing armpits',
'is waxing back',
'is waxing chest',
'is waxing eyebrows',
'is waxing legs',
'is weaving a basket',
'is weaving fabric',
'is welding',
'is whistling',
'is windsurfing',
'is winking',
'is doing wood burning (art)',
'is wrapping a present',
'is wrestling',
'is writing',
'is spinning yarn',
'is yawning',
'is doing yoga',
'is doing Zumba'
            ]

 """
 A set of physical signals extracted from The emotion thesaurus: A writer's guide to character expression [Puglisi et al.]
 """
    new_set_800 = [
'has a death grip on a purse',
'has a belly laugh',
'has a bent back',
'has a bent neck',
'has a bitter smile',
'has a body that curls in on itself',
'has a bowed head',
'has a clenched jaw',
'has a collapsed body posture',
'has a confrontational stance',
'has a corded neck',
'has a deliberate eyebrow raise',
'has a deliberate lowering of the head',
'has a distant or empty stare',
'has a downturned mouth',
'has a downward gaze',
'has a drunken behavior',
'has a exposed the neck',
'has a fight response',
'has a flat look',
'has a flush visible in the cheeks',
'has a flushed appearance',
'has a gaunt appearance',
'has a grimace or pained look',
'has a hand casually anchored on the hip',
'has a hand flap that dismisses the person or their idea',
'has a hand fluttering to the lips or neck',
'has a hand pressing against the throat or breastbone',
'has a hanging head',
'has a hard, distinctive jaw line',
'has a harried appearance',
'has a head that tips back, exposing the neck',
'has a head tilt',
'has a high chin',
'has a hunched posture',
'has a lidded look of satisfaction',
'has a mouth that curls with dislike, sneering',
'has a pained expression',
'has a pained gaze',
'has a pained or watery gaze',
'has a pained stare',
'has a pinched expression',
'has a pinched mouth',
'has a pouty bottom lip',
'has a red face and neck',
'has a relaxed physique',
'has a runny nose',
'has a set jaw',
'has a shiny face',
'has a silly grin',
'has a slack expression',
'has a smile that appears tight',
'has a stiff neck',
'has a stony expression',
'has a straight posture',
'has a tension-filled expression',
'has a thrust-out chest',
'has a tilted-back head',
'has a two-fingered salute',
'has a welcoming stance',
'has a wide grin',
'has a wide, open stance',
'has a wrinkled brow',
'has a wrinkled nose',
'has a yearning look',
'has aggression',
'has an arm hooked over the back of a chair',
'has an expression that appears pained',
'has an intense focus',
'has an intense, fevered stare',
'has an inward focus',
'has an open mouth',
'has an overall lifting of the facial countenance',
'has an overall visage that glows',
'has an unclean home, room, or office space',
'has an unkempt appearance',
'has an upturned face',
'has angry tears',
'has arms crossing in front of the chest',
'has arms hanging at the sides',
'has arms straight',
'has arms thrown wide',
'has beads of sweat on the lip or forehead',
'has blotchy skin',
'has bodies pressing against one another to become one',
'has body and feet pointed forward',
'has body posture that loosens or collapses',
'has body posture that perks up',
'has body turning away',
'has brows drawing closer',
'has brows pulled down (furrowed)',
'has bulging eyes',
'has bulky or dull clothing choices',
'has bumping shoulders',
'has chin dipping to the chest',
'has chin poking forward',
'has closed body language',
'has crossed arms',
'has dark circles under the eyes',
'has darting gaze',
'has direct eye contact',
'has downturned facial features',
'has ears that turn red',
'has elbows on the knees',
'has elbows pressed to the sides',
'has elbows tucking into the sides',
'has exposed neck',
'has eyebrows lowering and pinching together',
'has eyebrows raised',
'has eyebrows squeezing together',
'has eyes brimming with happy tears',
'has eyes crinkled shut',
'has eyes lit with a twinkle of mischief',
'has eyes open wide',
'has eyes shining, glossing over, and softening',
'has eyes staring at the ceiling',
'has eyes that appear red',
'has eyes that are bright, glossy',
'has eyes that look tired',
'has eyes that sparkle or shine',
'has eyes that widen slightly',
'has eyes tightly closed',
'has eyes wide and staring',
'has eyes widening',
'has eyes with a twinkle of mischief',
'has face tightening',
'has feet and torso facing the advantage',
'has feet angling out',
'has fingers clutching at shoulders',
'has fingers forming a steeple',
'has fingers lacing across the belly',
'has fingers loosely clasped in one\'s lap',
'has fingers retracting',
'has fingers turning claw\-like',
'has fists clenched',
'has fists on hips, elbows wide',
'has gaze looking up',
'has hair lifting on the nape and arms',
'has half-closed eyes',
'has hands behind the head',
'has hands clasped together ',
'has hands curling around one\'s middle',
'has hands jammed into armpits',
'has hands laying in the lap',
'has hands locked into fists',
'has hands on the knees',
'has hands raised into the air',
'has hands self-hugging',
'has hands that hang loosely at the sides',
'has hands tightening into fists',
'has hands touching the lips, mouth, face',
'has hands up, backing away with a shudder',
'has hands up, backing away',
'has hands up',
'has head lifted high, exposing the neck',
'has head resting on one\'s hand',
'has head thrown back',
'has head tilting away',
'has head tilting back',
'has head tilting slightly to the side',
'has heads that tip back, exposing the neck',
'has holding a hand up, warding others off',
'has hunched shoulders',
'has illness',
'has inappropriate responses ',
'has intense eye contact',
'has jumpiness',
'has knees pulling together',
'has languorous stretches',
'has lank or unwashed hair',
'has laugh lines',
'has leg muscles tightening',
'has legs that are planted wide',
'has legs wide apart',
'has limp posture',
'has lips parting',
'has lips pressed flat',
'has lips pressing tight',
'has lips pulling back, baring the teeth',
'has lips that flatten or curl',
'has narrowed eyes',
'has nervous behaviors for example',
'has nose-wrinkling',
'has nostrils flaring',
'has open body posture',
'has open palms held behind the back',
'has overlong nails',
'has palms hidden ',
'has palms stuffed into pockets',
'has palms',
'has passive destructiveness',
'has protruding eyes',
'has puffy face or eyes',
'has raised eyebrows',
'has raised, prominent cheekbones from smiling',
'has red-rimmed eyes',
'has relaxed arms',
'has relaxed posture',
'has rigid and defined forearm muscles',
'has rigid body posture',
'has rigid muscles',
'has rumpled clothing',
'has running makeup',
'has runny nose, sniffing',
'has saggy posture, bent neck',
'has saggy posture',
'has self-petting gestures',
'has shoulders back',
'has shoulders curling forward',
'has shoulders drawing forward',
'has shoulders drawing up',
'has shoulders dropping or slumping',
'has shoulders dropping',
'has shoulders hunching slightly',
'has shoulders lowered and loose',
'has shoulders rise and pull forward',
'has shoulders slumping',
'has shoulders that curl over the chest',
'has signs of letting oneself go ',
'has signs of letting oneself go',
'has skin bunching around the eyes',
'has skin stretched into a snarl',
'has skin tightening or hardening',
'has slightly parting the legs',
'has slouched body posture',
'has slumped posture',
'has slumped shoulders',
'has softened features that imply calm',
'has sparkling eyes, a weightless gaze',
'has spittle building up in the corners of the mouth',
'has spittle flying while yelling',
'has splotchy skin',
'has squinting, tightening eyes',
'has stalling gestures',
'has steps that drag',
'has stooped posture',
'has strained muscles',
'has strong posture (shoulders back, chest out, chin high)',
'has sweeping arm gestures',
'has tangled hair',
'has tears',
'has tendons standing out',
'has tension in the face, shoulders and neck',
'has the body conforming to whatever surface it rests on',
'has the body contorting',
'has the body freezing in place',
'has the body lacking tension',
'has the body ready to run',
'has the body sagging while seated',
'has the cheeks going lightly pink with pleasure',
'has the chest hitching as a sob is choked down',
'has the chest puffing out',
'has the chin dipping down',
'has the chin resting on the chest',
'has the fingers touching parted lips',
'has the head pulling back',
'has the head recoiling from the source',
'has the head tilting slightly to the side',
'has the mouth falling open',
'has the neck disappearing',
'has the nose crinkling',
'has the skin flushing',
'has tight muscles',
'has tight shoulders',
'has tightening under the eyes',
'has tightness in the face',
'has toes curling up',
'has torso and feet pointing toward the loved one',
'has unshaven cheeks',
'has unwashed clothes',
'has unwashed hair',
'has wide eyes, showing the whites',
'has widening eyes',
'has widening or bulging eyes, a double take',
'has wrinkled clothes',
'has yawns',
'is adjusting clothing',
'is adopting a sullen look',
'is adopting a wide, open stance',
'is angling away from those bearing witness to shame',
'is arguing with someone',
'is arguing with the suspect',
'is arguing',
'is arm stroking'
'is attempting to hide',
'is averting or lowering the gaze',
'is avoiding direct eye contact',
'is backing up',
'is barreling toward someone',
'is bearing the teeth',
'is beating at walls or surrounding objects',
'is being rude',
'is bending forward, laying head on arms',
'is bending the neck forward',
'is biting lips',
'is biting or picking at the fingernails',
'is biting the fingernails',
'is blowing a kiss',
'is blubbering',
'is blushing',
'is bowing',
'is bringing the legs up close to the body\'s core',
'is bullying',
'is bursting out in laughter',
'is cackling',
'is caretaking',
'is celebrating ',
'is chest bumping with others',
'is chewing on a knuckle',
'is choosing the middle, not the sides (be it a couch or a room)',
'is chuckling',
'is clamping a hand across one\'s mouth and applying pressure',
'is clapping someone on the back',
'is clapping the hands over the ears',
'is clapping',
'is clasping another\'s hand or forearm',
'is clasping hands behind the back',
'is clasping one\'s arms in a self-soothing gesture',
'is clasping one\'s forearms',
'is clasping the hands in front of the groin or other sensitive area',
'is clawing at the cheeks, dragging the fingers down',
'is clinging to loved ones',
'is closing a jacket',
'is closing or curling the hands inward',
'is closing the eyes to savor the experience',
'is closing the eyes',
'is clumsy',
'is clutching a coat',
'is clutching a purse',
'is clutching an object',
'is clutching at another person for support',
'is clutching at oneself',
'is clutching the hands',
'is clutching the stomach',
'is clutching the throat or chest',
'is collapsing onto a chair or bench',
'is compressing the lips while someone else speaks',
'is coughing',
'is covering one\'s face with the hands',
'is covering one\'s smile with a hand',
'is covering one\'s wrists',
'is covering oneself',
'is covering the face',
'is covering the head',
'is covering the mouth',
'is cracking knuckles',
'is cradling one partner\'s head while kissing',
'is cringing and rubbing one\'s palm against the chest (above one\'s heart)',
'is cringing or shaking',
'is crossing the arms',
'is crossing the legs',
'is crumpling onto a seat',
'is crying with the person',
'is crying, wailing, begging for help',
'is crying',
'is curling the toes',
'is curling up to take up less space',
'is curtseying',
'is destroying one\'s own possessions',
'is digging for tissues',
'is disorganized',
'is displaying affection with friends or loved ones',
'is displaying poor balance and coordination',
'is doing catlike stretches',
'is doing playful shoving',
'is doing satisfactory, catlike stretches',
'is doodling hearts and names',
'is doodling',
'is dosing off',
'is drawing the limbs close to the body',
'is drinking caffeinated beverages or energy drinks',
'is drinking',
'is dropping the head, while eyes closed',
'is dry washing the hands',
'is ducking one\'s chin to hide the neck',
'is ducking one\'s chin',
'is eating',
'is eavesdropping',
'is embracing someone else',
'is engaging excitedly with others',
'is engaging in small talk with people nearby',
'is enjoying a moment',
'is enjoying an event',
'is entering another’s personal space to intimidate',
'is exchanging knowing looks with others',
'is exploring the senses',
'is exposing the neck',
'is expressing concern',
'is expressing skepticism',
'is falling against someone, shoulder to shoulder',
'is falling asleep in odd places at odd times',
'is falling asleep while laying out by the pool',
'is falling asleep while watching TV',
'is falling to the ground',
'is fanning oneself',
'is fiddling with an object to avoid eye contact',
'is fiddling with the hands',
'is fidgeting, squirming',
'is finding something close to hand to use as a weapon ',
'is fingering jewelry for comfort',
'is fist pumping',
'is flaring nostrils',
'is flicking a hand in front of one\'s nose',
'is flinching when touched',
'is flipping hair back',
'is flipping through brochures or other reading material at hand',
'is flipping through TV channels',
'is flirting',
'is folding the hands',
'is following a person',
'is forming a steeple with hands and pressing them to lips',
'is friendly',
'is frowning',
'is gasping for air',
'is gasping',
'is gazing at someone, full of love',
'is gazing with focus',
'is getting drunk or high',
'is getting into someone\'s personal space',
'is giggling',
'is giving a high five',
'is giving a toast or praise',
'is giving someone an easy nod',
'is giving someone the thumbs-up',
'is glancing about for help',
'is glancing around uneasily',
'is glancing at one\'s watch',
'is glancing at the clock',
'is glancing at the doorway',
'is glancing at the phone',
'is glaring',
'is gossiping',
'is grabbing onto someone',
'is grabbing onto someone\'s arm',
'is grabbing the hair in clumps',
'is grimacing',
'is grinning',
'is gripping a fistful of someone\'s shirt at the chest level',
'is gripping nearby objects for support',
'is gripping one\'s own throat',
'is gripping one\'s own wrist',
'is gripping people for support',
'is gripping something',
'is gripping the sides of the head as if to cover the ears',
'is hands moistening',
'is handshaking with someone',
'is having a haunted look'
'is having a soured expression',
'is having good posture',
'is hiding behind a book',
'is holding a hand up',
'is holding an object close',
'is holding hands behind the back',
'is holding hands',
'is holding one\'s head',
'is holding one\'s sides',
'is holding oneself tightly clutching the arms',
'is holding oneself tightly wrapping arms around the belly',
'is holding onto a chair or wall for support',
'is holding onto the shoulders',
'is holding the elbows tight at one\'s sides',
'is holding the hands loosely behind the back',
'is holding the head in the hands',
'is holding the stomach',
'is hooking a hand in the other person’s belt or pocket',
'is hooking thumbs into one\'s belt loops',
'is hooting',
'is hosting an event',
'is hovering at the door or by the phone',
'is hugging someone',
'is hunching one\'s shoulders',
'is hunching over',
'is ignoring something being handed over',
'is increasing one’s personal distance from others',
'is inflicting pain on oneself',
'is initiating physical contact with others',
'is insulting the target in front of others',
'is inviting another into one\'s personal space',
'is issuing a challenge to the rival that contains an element of risk',
'is jabbing a finger in someone\'s face',
'is jerking away from contact',
'is keeping one\'s back to a wall or corner',
'is kicking at nearby objects',
'is kicking things',
'is kicking',
'is lacing fingers behind the head',
'is lashing out at others to transfer anger or blame',
'is laughing to oneself',
'is laughing',
'is laying a hand on someone\'s back or shoulder',
'is laying in bed with no motivation to get up',
'is laying the head down on the table',
'is laying the head on the arms',
'is leading rather than following',
'is leaning against a doorjamb or wall',
'is leaning against one another',
'is leaning against supports instead of standing tall on one\'s own',
'is leaning back in a chair',
'is leaning back in one\'s seat',
'is leaning back or away',
'is leaning back, an arm hooked over the back of a chair',
'is leaning back, at ease and in control',
'is leaning closer',
'is leaning forward',
'is leaning in',
'is leaning or turning away from the person making the request',
'is leaning with the shoulders bowing over the chest',
'is letting one\'s long hair slide across the shoulder',
'is letting out a heavy sigh',
'is licking one\'s lips',
'is lifting a hand loosely, palm up in a "Who cares?" gesture',
'is lifting someone up ',
'is lifting the chin',
'is lifting the heels',
'is lightly stroking a forearm',
'is lightly touching a shoulder',
'is limbering up shoulders and neck as if readying to fight',
'is listening to someone',
'is listening while participating in another activity',
'is looking all around, especially behind',
'is looking around in confusion or shock',
'is looking around',
'is looking away',
'is looking down',
'is looking pale'
'is looking past someone rather than at them',
'is looking sleepy or glazed',
'is looking up at the sky',
'is looking up with hands raised in the why me? position',
'is looking up',
'is looming over the target ',
'is looping the thumbs in the front pockets',
'is lowering one\'s head',
'is lowering the chin to look down on someone',
'is lying down',
'is lying in the other’s lap',
'is lying on the grass to soak up the sun',
'is lying on the grass',
'is making faces',
'is making one\'s body as small as possible',
'is massaging the temples, as if weary',
'is medicating',
'is melding to each other\'s curves',
'is mimicking body language of another person',
'is mimicking boredom',
'is mocking someone',
'is moistening one’s lip',
'is moving closer to erase distance',
'is moving to get closer or touch',
'is moving toward an exit',
'is narrowing eyes',
'is narrowing one\'s stance, bringing the feet together',
'is narrowing the eyes',
'is not engaging in conversation',
'is observing',
'is offering a bemused smile',
'is offering a conspiratorial gesture to someone ',
'is offering a deep sigh',
'is offering a gift or favor of appreciation',
'is offering a thoughtful expression',
'is offering a wave',
'is offering encouragement and support',
'is offering small touches to connect',
'is pacing',
'is panting',
'is participating in relaxing activities',
'is patting a leg in comfort',
'is people watching',
'is phoning or texting ',
'is picking at food ',
'is picking at lint',
'is picking at skin',
'is picking at the fingernails',
'is picking fights',
'is pinching the bridge of the nose',
'is pinching the skin at the throat',
'is pinning the arms against the stomach',
'is placing a hand on the chest',
'is placing fingertips against one\'s open mouth',
'is placing hands in one\'s pockets',
'is placing the hands behind the head',
'is placing the palm of a hand over one\'s heart',
'is planting the feet wide apart',
'is plucking at clothes to cool down',
'is pointing a finger ',
'is pointing and jabbing the air for emphasis',
'is pointing one\'s knees toward the other in invitation',
'is pointing one\'s torso and feet toward another person',
'is pointing with an index finger',
'is poking one\'s tongue into the cheek',
'is poking or prodding at something',
'is pounding one’s fist against thighs, table, a wall, etc.',
'is pouting',
'is praying',
'is pressing a fist to the mouth',
'is pressing a hand against the breastbone',
'is pressing a hand to the abdomen',
'is pressing a palm over the lips to hold back a cry',
'is pressing fingers to smiling lips',
'is pressing fists to the sides of the head',
'is pressing hands against cheeks',
'is pressing hands against the stomach',
'is pressing hands to one\'s temples',
'is pressing knees together',
'is pressing lips together',
'is pressing oneself against one\'s partner',
'is pretending to faint',
'is propping one\'s head up with a hand',
'is propping the head up with fist',
'is prying or snooping',
'is puffing out the cheeks',
'is pulling a ball cap low',
'is pulling a hood over the head',
'is pulling and tugging at one\'s clothes',
'is pulling arms and legs in toward the core',
'is pulling at the collar',
'is pulling away if touched',
'is pulling books or packages tightly against the chest',
'is pulling closer',
'is pulling down eyebrows in concentration',
'is pulling down glasses and looking over the rims',
'is pulling hair',
'is pulling loved ones close to protect them',
'is pulling on someone\'s sleeve',
'is pulling one\'s clothing to loosen',
'is pulling or tugging at one\'s clothes',
'is pulling or tugging on an ear',
'is pulling or twisting at one\'s hair',
'is pulling out a weapon ',
'is pulling someone against the shoulder',
'is pulling someone close',
'is pulling someone into a side hug',
'is pulling stunts or pranks to regain attention',
'is pulling up a collar to cover the mouth and nose',
'is punching',
'is pursing the lips',
'is pushing and shoving',
'is pushing one\'s glasses up',
'is pushing the back of the hand against one\'s nose',
'is putting a hand over the face',
'is putting an arm around someone’s shoulders',
'is putting distance between oneself and the other person',
'is putting one\'s hands in one\'s pockets',
'is raising a hand to ward off others',
'is raising one\'s palms to the sky',
'is reaching out to brush, touch or grasp',
'is reaching out to cause pain',
'is reaching out to steady oneself',
'is reaching out to throttle, hit, or cause pain',
'is reaching past a gap between buttons to touch warm skin',
'is reaching',
'is reacting defensively',
'is reclining on a couch or floor',
'is refusing to look',
'is refusing to respond or engage',
'is responding with anger by punching',
'is responding with anger by shoving',
'is resting the chin in the hand',
'is retracting the arms, bringing them close to the torso',
'is retreating into the fetal position or curling up',
'is retreating',
'is rising up slightly to emphasize words',
'is rolling the eyes',
'is rolling the neck and shoulders',
'is rolling the neck',
'is rolling up sleeves or loosing a collar',
'is rubbing a hand self-consciously through one\'s hair',
'is rubbing at one\'s exposed forearms',
'is rubbing at one\'s face and eyes',
'is rubbing at one\'s hands',
'is rubbing at or massaging one\'s chest as if pained',
'is rubbing at the back of one\'s neck',
'is rubbing at the pained area',
'is rubbing one\'s arms and looking around',
'is rubbing one\'s arms',
'is rubbing one\'s forehead or eyebrows',
'is rubbing one\'s hands against clothing to dry them',
'is rubbing one\'s hands on pant legs',
'is rubbing or pressing a fist against the chest',
'is rubbing someone\'s back',
'is rubbing the arms or legs',
'is rubbing the back of the neck without making eye contact',
'is rubbing the chin',
'is rubbing the ears',
'is rubbing the hands over one\'s clothing',
'is rubbing the heel of a palm against chest',
'is rubbing the neck',
'is rubbing the nose',
'is rubbing the wrists ',
'is running hands through other person\'s hair',
'is running hands through the hair',
'is running one\'s palms over the other\'s sleeves',
'is running the hands through the hair',
'is sagging against a door or wall',
'is sagging in a chair',
'is scowling',
'is scraping one\'s palms against clothing as if to rid them of something',
'is scratching at one\'s cheek or temple',
'is scratching or rubbing skin',
'is scratching',
'is screaming',
'is scrubbing a hand over the face',
'is seeking corners in confined spaces',
'is shaking out the arms',
'is shaking out the hands and arms',
'is shaking out the hands',
'is sharing a happy glance with someone',
'is shielding the body',
'is shifting about',
'is shouting',
'is shoving hands in pockets',
'is shoving people aside to reach the enemy',
'is shoving, pushing',
'is showing off',
'is showing one\'s palms',
'is showing that interest is lacking',
'is showing the teeth',
'is shrugging',
'is shutting a door',
'is sitting bent over',
'is sitting limply',
'is sitting up, straight and alert',
'is sitting with legs touching the other person\'s',
'is skimming fingertips along the jaw line',
'is slam-dunking trash into a barrel after a game or event',
'is slamming a door',
'is slamming cupboards or drawers',
'is slapping one\'s knees or thighs',
'is sleeping',
'is sliding down in a chair',
'is slightly parting the legs',
'is slinking away',
'is slouching in a chair with one\'s arms dangling',
'is slouching',
'is slumping rather than sitting straight',
'is smiling at nothing',
'is smiling through tears',
'is smiling',
'is smirking as another speaks',
'is smoking ',
'is smoothing the front of a shirt',
'is snapping a pencil',
'is sneaking or spying',
'is sneering',
'is sniffing, wiping at nose',
'is sobbing or weeping',
'is speaking through the teeth with forced restraint',
'is speed-talking with others, heads close together, gossipy',
'is spewing food or drink',
'is spinning around, trying to spot any and all danger',
'is spinning away in a huff',
'is spinning away',
'is spitting at someone or in their direction',
'is spitting',
'is sprawling on a bed',
'is sprawling on a couch',
'is spreading the fingers out in a fan against the breastbone',
'is sprinting or running',
'is squealing',
'is squeezing a shoulder or hand',
'is squeezing eyes shut',
'is squeezing someone\'s arm to the point of bruising',
'is squeezing the eyes shut, refusing to look',
'is squeezing the eyes tight',
'is squinting',
'is squirming in discomfort',
'is stalking away from someone',
'is standing tall with good posture, legs spread wide',
'is standing with hands tucked in one\'s armpits',
'is standing with one arm holding the other at the elbow',
'is staring at nothing',
'is staring blankly or emotionlessly',
'is staring down at one\'s empty hands',
'is staring down at one\'s feet',
'is staring down at one\'s hands',
'is staring down at the ground',
'is staring off into space',
'is staring someone down to frighten them',
'is staring the target down',
'is staring',
'is sticking the tongue out',
'is stomping up the stairs',
'is stopping mid-stride or stumbling',
'is straining to hear, shushing others to be quiet',
'is stretching out the legs',
'is stretching the arms out wide',
'is stretching',
'is stroking and squeezing',
'is stroking one\'s arm',
'is stroking one\'s own neck',
'is stroking one\'s own throat',
'is stroking or smoothing someone\'s hair',
'is stroking the throat',
'is stumbling back a step',
'is stumbling mid-stride',
'is supporting the head with a hand',
'is surveying the finished product with a pleased expression',
'is swatting at the air',
'is swearing',
'is sweating',
'is sweeping a hand across the forehead to get rid of sweat',
'is swinging someone around',
'is taking a deep, pained breath',
'is taking a slight step back',
'is taking a step closer',
'is taking a step toward the person or object one wants',
'is taking extra care with one\'s appearance',
'is taking up space (legs spread wide, arms loose at the sides)',
'is texting during an event or while someone speaks',
'is texting or web surfing on the phone',
'is threatening violence',
'is throwing hands up in an "I give up" gesture',
'is throwing things',
'is throwing up',
'is thrusting the chest out',
'is thrusting the pelvis forward',
'is thumbing the ear',
'is tilting the body toward the source',
'is tilting the chin down and frowning',
'is tilting the head to the ceiling',
'is tilting the head to the side',
'is tilting the head',
'is tingling fingers and toes',
'is tipping the head back',
'is tossing and turning in bed, an inability to sleep',
'is touching a cross or fingering jewelry for comfort',
'is touching affectionately',
'is touching another person\'s hand',
'is touching one\'s fingertips together in a steeple',
'is touching or stroking one\'s own throat',
'is touching others to get their attention ',
'is touching someone to test the connection',
'is touching the base of the neck',
'is touching the other\'s face',
'is touching the throat',
'is toying with items',
'is toying with one\'s jewelry to release nervous tension',
'is tripping',
'is trying to get rid of a bad smell',
'is tugging a hat down low',
'is tugging at clothing',
'is tugging down the sleeves',
'is tugging one\'s hair',
'is turning away',
'is turning one\'s body slightly rather than facing others directly',
'is turning the body at an angle instead of facing the subject head-on',
'is turning the face to the sun, eyes closed',
'is turning the head to the side',
'is twisting a watch or ring',
'is twisting one\'s neck as if sore',
'is twisting the mouth',
'is unable to meet someone\'s eyes',
'is unable to sleep',
'is unbuttoning the top button of a shirt',
'is using a friend\'s shoulder as a shelf for the elbow',
'is using a purse or jacket to create a shield',
'is using a strong, businesslike handshake',
'is using the body to nudge, push, or block',
'is uttering a scream or war cry',
'is vandalizing one\'s own things',
'is waiting at a window',
'is walking away',
'is walking out of the room',
'is walking stiffly',
'is walking with the locked knees',
'is walking with wide steps',
'is walking',
'is warding others off',
'is warding someone off',
'is warding something off',
'is watching others to see their reactions',
'is watching others',
'is watching romantic movies',
'is watching the door',
'is waving dismissively',
'is waving enthusiastically',
'is waving the arms, using grand gestures',
'is weaving hands into the hair',
'is wetting the lips',
'is wincing',
'is winking or giving someone an easy nod',
'is winking',
'is withdrawing from others',
'is wrenching an enemy\'s arm to stop them from leaving',
'is wrenching an someone\'s arm',
'is wringing one\'s hands',
'is wrinkling one\'s nose',
'is wrinkling the nose like there\'s a bad smell',
'is writing notes',
'is writing poetry to another person',
'is yawning',
'is yelling',
    ]

    return new_set_800 , gender_age, locContext, kinetic + ucf_HMDB
